name: test error

on:
  workflow_dispatch: # Cho phép chạy workflow thủ công từ giao diện GitHub

jobs:
  setup-chrome-rd:
    runs-on: windows-latest # Chạy trên máy ảo Windows mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 1
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile "chrome_setup.exe"
          Start-Process "chrome_setup.exe" -ArgumentList "/silent /install" -Wait

      - name: 2
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chrome_remote_desktop_host.msi"
          Start-Process "msiexec.exe" -ArgumentList "/i", "chrome_remote_desktop_host.msi", "/quiet" -Wait
      
      - name: 3
        run: |
               DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0Ab_5qlk79HhQgQZMOGstqe6KwuJ1Sd5kWTGY51EGrs7lIpnrBJm2gpXBcaTIDd0fl7rbVA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) --pin=111111
           
      - name: Wait
        run: |
          Start-Sleep -Seconds 2147483
      - name: Wait2
        run: |
          Start-Sleep -Seconds 2147483

          
